language: java

jdk: oraclejdk8

os: linux

install: true
  
before_script:
  - echo "MAVEN_OPTS='-Xmx2g -XX:MaxPermSize=512m'" > ~/.mavenrc
  - git clone https://github.com/turnus/turnus.cli.git
  
script: mvn clean install
